function costs = cost_calculation (costs, i, cost_type, eNBs_num_in_same_TAL)
%%                                                        Part - Costs format

%                                                            costs(struct type)
%                                                                       |
%                                                                       |
%                           -----------------------------------------------
%                           |            |            |            |            |            |            |            |     
%                           |            |            |            |            |            |            |            |           
%                      time_1                time_2        ......               .......                     time_n     
%                                                      |
%                                  ...                 |             ....
%                          -----------------------------------
%                          |               |               |                 |                 | 
%                   eNB_cost  MME_cost  SGW_cost  PGW_cost    total_cost
%                     /      \
%                    /        \
%      messages        bytes

%%                                                      Part - Costs Calculation 

switch cost_type
    case 'handover_with_TAU'
        %% cost calculation for handover with TAU
        costs.handover_with_TAU.(['time_', int2str(i)]).UE_requests = ... 
            costs.handover_with_TAU.(['time_', int2str(i)]).UE_requests + 1;
        costs.handover_with_TAU.(['time_', int2str(i)]).UE_cost.messages =...
            costs.handover_with_TAU.(['time_', int2str(i)]).UE_cost.messages + 9;
        costs.handover_with_TAU.(['time_', int2str(i)]).UE_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).UE_cost.bytes + 446;
        costs.handover_with_TAU.(['time_', int2str(i)]).eNB_cost.messages = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).eNB_cost.messages + 23;
        costs.handover_with_TAU.(['time_', int2str(i)]).eNB_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).eNB_cost.bytes + 765;
        costs.handover_with_TAU.(['time_', int2str(i)]).MME_cost.messages =  ...
            costs.handover_with_TAU.(['time_', int2str(i)]).MME_cost.messages + 20;
        costs.handover_with_TAU.(['time_', int2str(i)]).MME_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).MME_cost.bytes + 608;
        costs.handover_with_TAU.(['time_', int2str(i)]).PGW_cost.messages = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).PGW_cost.messages + 4;
        costs.handover_with_TAU.(['time_', int2str(i)]).PGW_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).PGW_cost.bytes + 81;
        costs.handover_with_TAU.(['time_', int2str(i)]).SGW_cost.messages = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).SGW_cost.messages + 9;
        costs.handover_with_TAU.(['time_', int2str(i)]).SGW_cost.bytes = ...
             costs.handover_with_TAU.(['time_', int2str(i)]).SGW_cost.bytes + 268;
        costs.handover_with_TAU.(['time_', int2str(i)]).PCRF_cost.messages = ...
             costs.handover_with_TAU.(['time_', int2str(i)]).PCRF_cost.messages + 2;
        costs.handover_with_TAU.(['time_', int2str(i)]).PCRF_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).PCRF_cost.bytes +  42;
        costs.handover_with_TAU.(['time_', int2str(i)]).total_cost.messages = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).total_cost.messages + 58;
        costs.handover_with_TAU.(['time_', int2str(i)]).total_cost.bytes = ...
            costs.handover_with_TAU.(['time_', int2str(i)]).total_cost.bytes + 1764;
    case 'cell_reselection_with_TAU'
        %% cost calculation for cell_reselection with TAU
       costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_requests = ... 
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_requests + 1;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_cost.messages =...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_cost.messages + 9;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).UE_cost.bytes + 691;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).eNB_cost.messages = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).eNB_cost.messages + 14;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).eNB_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).eNB_cost.bytes + 313;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).MME_cost.messages =  ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).MME_cost.messages + 7;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).MME_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).MME_cost.bytes + 163;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PGW_cost.messages = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PGW_cost.messages + 4;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PGW_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PGW_cost.bytes + 81;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).SGW_cost.messages = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).SGW_cost.messages + 4;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).SGW_cost.bytes = ...
             costs.cell_reselection_with_TAU.(['time_', int2str(i)]).SGW_cost.bytes + 78;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PCRF_cost.messages = ...
             costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PCRF_cost.messages + 2;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PCRF_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).PCRF_cost.bytes +  42;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).total_cost.messages = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).total_cost.messages + 31;
        costs.cell_reselection_with_TAU.(['time_', int2str(i)]).total_cost.bytes = ...
            costs.cell_reselection_with_TAU.(['time_', int2str(i)]).total_cost.bytes + 677;
    case 'periodic_TAU'
        %% cost calculation for periodic TAU
        costs.periodic_TAU.(['time_', int2str(i)]).UE_requests = ... 
            costs.periodic_TAU.(['time_', int2str(i)]).UE_requests + 1;
        costs.periodic_TAU.(['time_', int2str(i)]).UE_cost.messages =...
            costs.periodic_TAU.(['time_', int2str(i)]).UE_cost.messages + 6;
        costs.periodic_TAU.(['time_', int2str(i)]).UE_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).UE_cost.bytes + 341;
        costs.periodic_TAU.(['time_', int2str(i)]).eNB_cost.messages = ...
            costs.periodic_TAU.(['time_', int2str(i)]).eNB_cost.messages + 11;
        costs.periodic_TAU.(['time_', int2str(i)]).eNB_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).eNB_cost.bytes + 313;
        costs.periodic_TAU.(['time_', int2str(i)]).MME_cost.messages =  ...
            costs.periodic_TAU.(['time_', int2str(i)]).MME_cost.messages + 7;
        costs.periodic_TAU.(['time_', int2str(i)]).MME_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).MME_cost.bytes + 163;
        costs.periodic_TAU.(['time_', int2str(i)]).PGW_cost.messages = ...
            costs.periodic_TAU.(['time_', int2str(i)]).PGW_cost.messages + 4;
        costs.periodic_TAU.(['time_', int2str(i)]).PGW_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).PGW_cost.bytes + 81;
        costs.periodic_TAU.(['time_', int2str(i)]).SGW_cost.messages = ...
            costs.periodic_TAU.(['time_', int2str(i)]).SGW_cost.messages + 4;
        costs.periodic_TAU.(['time_', int2str(i)]).SGW_cost.bytes = ...
             costs.periodic_TAU.(['time_', int2str(i)]).SGW_cost.bytes + 78;
        costs.periodic_TAU.(['time_', int2str(i)]).PCRF_cost.messages = ...
             costs.periodic_TAU.(['time_', int2str(i)]).PCRF_cost.messages + 2;
        costs.periodic_TAU.(['time_', int2str(i)]).PCRF_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).PCRF_cost.bytes +  42;
        costs.periodic_TAU.(['time_', int2str(i)]).total_cost.messages = ...
            costs.periodic_TAU.(['time_', int2str(i)]).total_cost.messages + 28;
        costs.periodic_TAU.(['time_', int2str(i)]).total_cost.bytes = ...
            costs.periodic_TAU.(['time_', int2str(i)]).total_cost.bytes + 677;
    case 'paging'
        %% cost calculation for paging
        costs.paging.(['time_', int2str(i)]).UE_requests = ... 
            costs.paging.(['time_', int2str(i)]).UE_requests + 1;
        costs.paging.(['time_', int2str(i)]).UE_cost.messages =...
            costs.paging.(['time_', int2str(i)]).UE_cost.messages + 5;
        costs.paging.(['time_', int2str(i)]).UE_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).UE_cost.bytes + 321;
        
        %paging would affects also all the other UEs & eNBs in the same TAL
        costs.paging.(['time_', int2str(i)]).eNB_cost.messages = ...
            costs.paging.(['time_', int2str(i)]).eNB_cost.messages + 8 ...
            + eNBs_num_in_same_TAL;
        costs.paging.(['time_', int2str(i)]).eNB_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).eNB_cost.bytes + 246 + ...
            37*eNBs_num_in_same_TAL;
        
        
        costs.paging.(['time_', int2str(i)]).MME_cost.messages =  ...
            costs.paging.(['time_', int2str(i)]).MME_cost.messages + 8;
        costs.paging.(['time_', int2str(i)]).MME_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).MME_cost.bytes + 162;
        costs.paging.(['time_', int2str(i)]).PGW_cost.messages = ...
            costs.paging.(['time_', int2str(i)]).PGW_cost.messages + 4;
        costs.paging.(['time_', int2str(i)]).PGW_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).PGW_cost.bytes + 81;
        costs.paging.(['time_', int2str(i)]).SGW_cost.messages = ...
            costs.paging.(['time_', int2str(i)]).SGW_cost.messages + 6;
        costs.paging.(['time_', int2str(i)]).SGW_cost.bytes = ...
             costs.paging.(['time_', int2str(i)]).SGW_cost.bytes + 111;
        costs.paging.(['time_', int2str(i)]).PCRF_cost.messages = ...
             costs.paging.(['time_', int2str(i)]).PCRF_cost.messages + 2;
        costs.paging.(['time_', int2str(i)]).PCRF_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).PCRF_cost.bytes +  42;
        costs.paging.(['time_', int2str(i)]).total_cost.messages = ...
            costs.paging.(['time_', int2str(i)]).total_cost.messages + 28 +...
            eNBs_num_in_same_TAL;
        costs.paging.(['time_', int2str(i)]).total_cost.bytes = ...
            costs.paging.(['time_', int2str(i)]).total_cost.bytes + 642 +...
            37*eNBs_num_in_same_TAL;
        %
end
end